# Generated by Django 2.1.7 on 2020-08-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200817_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='ekleyen',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='kategori',
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
