# Generated by Django 2.1.7 on 2020-08-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_auto_20200817_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siparisler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masa_no', models.IntegerField(verbose_name='Masa numarası')),
                ('masa_bosmu', models.BooleanField(verbose_name='Masa boşmu')),
                ('siparis_list', models.TextField(verbose_name='Sipariş Listesi')),
            ],
        ),
    ]
