# Generated by Django 2.1.7 on 2020-08-19 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_siparisler'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Siparisler',
            new_name='Masa',
        ),
    ]
