# Generated by Django 2.1.7 on 2020-08-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200820_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiparisKayitlari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masa_no', models.IntegerField(verbose_name='Masa No')),
                ('siparis_list', models.TextField(verbose_name='Siparis Listesi')),
                ('siparis_zamani', models.DateTimeField(auto_now_add=True)),
                ('kisi_sayisi', models.IntegerField(verbose_name='Kişi Sayısı')),
            ],
        ),
    ]
