# Generated by Django 2.1.7 on 2020-08-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_sipariskayitlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='sipariskayitlari',
            name='siparis_id',
            field=models.IntegerField(default=1, verbose_name='Sipariş id'),
            preserve_default=False,
        ),
    ]
