# Generated by Django 2.1.7 on 2020-08-22 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_sipariskayitlari_siparis_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siparis_list', models.TextField(verbose_name='Sipariş Listesi')),
                ('kisi_say', models.IntegerField(verbose_name='Kisi Say')),
            ],
        ),
        migrations.AddField(
            model_name='masa',
            name='kisi_say',
            field=models.IntegerField(default=2, verbose_name='Kisi Say'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sipariskayitlari',
            name='kisi_sayisi',
            field=models.IntegerField(default=1, verbose_name='Kişi Sayısı'),
        ),
        migrations.AlterField(
            model_name='sipariskayitlari',
            name='siparis_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sipariş id'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='masa_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Masa'),
        ),
    ]
