# Generated by Django 2.1.7 on 2020-08-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200822_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='kisi_say',
            field=models.IntegerField(default=1, verbose_name='Kisi Say'),
        ),
    ]
