# Generated by Django 2.1.7 on 2020-08-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_sipariskayitlari_siparis_kapanis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipariskayitlari',
            name='siparis_kapanis',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kapanış saati'),
        ),
    ]
