# Generated by Django 2.1.7 on 2020-09-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_masa_toplam_ucret'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='toplam_ucret',
            field=models.FloatField(default=1, verbose_name='Toplam ücret'),
            preserve_default=False,
        ),
    ]
