# Generated by Django 2.1.7 on 2020-08-18 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200817_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='aciklama',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Açıklama'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='resim',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='menu-resim/', verbose_name='Resim'),
            preserve_default=False,
        ),
    ]
