# Generated by Django 2.1.7 on 2020-08-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200818_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='resim',
            field=models.ImageField(null=True, upload_to='menu-resim/', verbose_name='Resim'),
        ),
    ]
