# Generated by Django 2.1.7 on 2020-08-18 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200818_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Kategori', verbose_name='Kategori'),
        ),
    ]
