# Generated by Django 2.1.7 on 2020-08-18 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200818_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='kategori',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='Kategori'),
            preserve_default=False,
        ),
    ]
