# Generated by Django 2.1.7 on 2020-08-19 17:31

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20200818_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='resim',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='menu-resim/', verbose_name='Resim'),
        ),
    ]
