# Generated by Django 2.1.7 on 2020-09-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20200903_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='porsiyon_0_5',
            field=models.FloatField(blank=True, null=True, verbose_name='Yarım Porsiyon Fiyat'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='porsiyon_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Bir Porsiyon Fiyat'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='porsiyon_1_5',
            field=models.FloatField(blank=True, null=True, verbose_name='Bir Buçuk Porsiyon Fiyat'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='porsiyon_2',
            field=models.FloatField(blank=True, null=True, verbose_name='İki Porsiyon Fiyat'),
        ),
    ]
